name: 'conventional-version-check'
description: 'read version content as conventional version'
inputs:
  sha-length:  # id of input
    description: 'length of short-sha to return'
    required: true
    default: '8'
outputs:
  sha: # output will be available to future steps
    description: 'commit of git full sha'
  short-sha:
    description: 'commit of git full sha short'
  tag-version:
    description: 'tag name when CI in refs/tags'
  cc-latest-version:
    description: 'version of latest conventional changelog'
  cc-latest-changes-log:
    description: 'content of latest conventional changelog'
  cc-latest-status:
    description: 'status of latest'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  color: blue
  icon: tag