name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: check-version
      with:
        sha-length: 8
    - name: check test out
      run: |
        echo "sha: ${{ steps.check-version.outputs.sha }}"
        echo "short-sha: ${{ steps.check-version.outputs.short-sha }}"
        echo "tag-version: ${{ steps.check-version.outputs.tag-version }}"
        echo "cc-latest-version: ${{ steps.check-version.outputs.cc-latest-version }}"
        echo "cc-latest-date: ${{ steps.check-version.outputs.cc-latest-date }}"
        echo "cc-latest-status: ${{ steps.check-version.outputs.cc-latest-status }}"
        echo "cc-latest-changes-log: ${{ steps.check-version.outputs.cc-latest-changes-log }}"
